#!/bin/bash

#   Where is the list of original FastQ files?
#       Include the full file path.
RAW_SAMPLES=/home/morrellp/liux1299/Shared/Datasets/NGS/Barley_Exome/WB_NAM/Raw_renamed/introgressed_samples.txt

#   Where are we storing the output files?
#       Final directory is ${OUT_DIR}/Name_of_Handler
OUT_DIR=/home/morrellp/liux1299/scratch/introgressed

#   Name this project
PROJECT=LianaPop_introgressed

#   What email should we use for job notifications?
EMAIL=liux1299@umn.edu

#   What encoding is used for quality values?
#       Look at the FastQC files to determine
#       the sequence encoding. Choose from:
#           'sanger', 'illumina'
#           'solexa', or 'phred'
PLATFORM=sanger

#   What reference genome are we using?
#       Include the full file path.
REF_GEN=/home/morrellp/liux1299/Shared/References/Reference_Sequences/Barley/Morex/barley_RefSeq_v1.0/barley_pseudomolecules_parts.fa

############################################
##########     GBS_Demultiplex    ##########
############################################

#   What are our QS
GD_QSUB="mem=1gb,nodes=1:ppn=4,walltime=6:00:00"

GBS_SAMPLES=

#   A key file with the following columns:
#       Flowcell Lane Barcode Sample PlateName Row Column
KEY_FILE=

#   Are the barcodes at the beginning or the end of the sequence?
#       Choose from: 'beginning' or 'end'
LINE_ENDING=

#   How many mismatches are allowed?
MISMATCH_TOL=1

#   Do we allow partial overlap?
PARTIAL=0

#   What extension or naming convention do the samples have?
FILE_TYPE=

############################################
##########   Quality_Assessment   ##########
############################################

#   What are our QSub settings for Quality_Assessment?
#       Below are the recommended settings
QA_QSUB="mem=4000mb,nodes=1:ppn=4,walltime=6:00:00"

#   Provide an alternate list of FastQ, SAM, or BAM files to be used, rather than RAW_SAMPLES
#       This is so you can use Quality_Assessment on samples other than your original FastQ files
#       Include the full file path.
ALTERNATE_SAMPLES=

############################################
##########       Read_Depths      ##########
############################################

#   What are our QSub settings for Read_Depths?
#       Below are the recommended settings
RD_QSUB="mem=4000mb,nodes=1:ppn=4,walltime=6:00:00"

#   Where is the list of FastQC zipfiles?
ZIP_FILES=${OUT_DIR}/Quality_Assessment/${PROJECT}_FastQC_ZipFiles.txt

#   What is the target size, or size of the genome/region that was sequenced?
TARGET=

############################################
##########    Adapter_Trimming    ##########
############################################

#   What are our QSub settings for Adapter_Trimming?
#       Below are the recommended settings
AT_QSUB="mem=1gb,nodes=1:ppn=8,walltime=10:00:00"

#   How are forward samples named?
#       Example: _1_sequence.txt.gz
FORWARD_NAMING=_R1_raw.fastq.gz

#   How are reverse samples named?
#       Example: _2_sequence.txt.gz
REVERSE_NAMING=_R2_raw.fastq.gz

#   If you have single-end samples, leave
#       FORWARD_NAMING and REVERSE_NAMING
#       filled with values that do NOT
#       match your samples

#	What is our adapter file? Include the full file path.
ADAPTERS=/home/morrellp/liux1299/Shared/References/Adapters/illumina_adapters.fa

#   What is Scythe's prior contamination rate?
PRIOR=0.05

############################################
##########    Quality_Trimming    ##########
############################################

#   What are our QSub settings for Quality_Trimming?
#       Below are the recommended settings
QT_QSUB="mem=1gb,nodes=1:ppn=8,walltime=10:00:00"

#   Where is our list of trimmed samples? Include the full file path.
ADAPTED_LIST=${OUT_DIR}/Adapter_Trimming/${PROJECT}_trimmed_adapters.txt

#   How are trimmed forward samples named?
#       If using the Adapter_Trimming handler,
#       leave the following definition as is
FORWARD_ADAPTED=_R1_raw_Single_ScytheTrimmed.fastq.gz

#   How are trimmed reverse samples named?
#       If using the Adapter_Trimming handler,
#       leave the following definition as is
REVERSE_ADAPTED=_R2_raw_Single_ScytheTrimmed.fastq.gz

#   How are trimmed single samples named?
#       If using the Adapter_Trimming handler,
#       leave the following definition as is
SINGLES_ADAPTED=_Single_ScytheTrimmed.fastq.gz

#   If you have single-end samples, leave
#       FORWARD_ADAPTED and REVERSE_ADAPTED
#       filled with values that do NOT
#       match your samples

#   If you have paired-end samples, leave
#       SINGLES_ADAPTED filled with values that
#       do NOT match your samples

#   What is the threshold for trimming?
#       Default trimming: 20
THRESHOLD=

############################################
##########  	Read_Mapping	  ##########
############################################

#   What are our QSub settings for Read_Mapping?
#       Below are the recommended settings
RM_QSUB="mem=14gb,nodes=1:ppn=12,walltime=24:00:00"

#   Where is our list of trimmed samples?
#       If you're using the list from Adapter_Trimming
#       TRIMMED_LIST=${OUT_DIR}/Adapter_Trimming/${PROJECT}_trimmed_adapters.txt
#       If you're using the list from Quality_Trimming
#       TRIMMED_LIST=${OUT_DIR}/Quality_Trimming/${PROJECT}_trimmed_quality.txt
#       Include the full file path.
TRIMMED_LIST=/panfs/roc/groups/9/morrellp/shared/Projects/WBDC_inversions/sequence_handling/WBDC_LianaPop/Adapter_Trimming/Liana_trimmed_list.txt

#   How are trimmed forward samples named?
#       If using the Adapter_Trimming handler
#       FORWARD_TRIMMED=_Forward_ScytheTrimmed.fastq.gz
#       If using the Quality_Trimming handler
#       FORWARD_TRIMMED=_R1_trimmed.fastq.gz
FORWARD_TRIMMED=_R1_Single_ScytheTrimmed.fastq.gz

#   How are trimmed reverse samples named?
#       If using the Adapter_Trimming handler
#       REVERSE_TRIMMED=_Reverse_ScytheTrimmed.fastq.gz
#       If using the Quality_Trimming handler
#       REVERSE_TRIMMED=_R2_trimmed.fastq.gz
REVERSE_TRIMMED=_R2_Single_ScytheTrimmed.fastq.gz

#   How are trimmed single-end samples named?
#       If using the Adapter_Trimming handler
#       SINGLES_TRIMMED=_Single_ScytheTrimmed.fastq.gz
#       If using the Quality_Trimming handler
#       SINGLES_TRIMMED=_single_trimmed.fastq.gz
SINGLES_TRIMMED=junk

#   BWA mem parameters; below are the defaults for BWA mem
#       How many threads are we using?
THREADS=8

#       What is our minimum seed length?
SEED=8

#       What is the band width?
WIDTH=100

#       What is our off-diagonal x-dropoff (Z-dropoff)?
DROPOFF=100

#       What is our re-seed value?
RE_SEED=1.0

#       What is our cutoff value?
CUTOFF=10000

#       What is our matching score?
MATCH=1

#       What is our mismatch penalty?
MISMATCH=4

#       What is our gap penalty?
GAP=8

#       What is our gap extension penalty?
EXTENSION=1

#       What is our clipping penalty?
CLIP=6

#       What is our unpaired read penatly?
UNPAIRED=9

#       Do we assume the first input query is interleaved?
INTERLEAVED=false

#       What is our minimum threshold?
THRESHOLD=85

#       Do we output all alignments, and mark as secondary?
SECONDARY=false

#       Do we append FASTA/Q comments to SAM files?
APPEND=false

#       Do we use hard clipping?
HARD=false

#       Do we mark split hits as secondary?
SPLIT=true

#       What is the verbosity level?
#           Choose from:
#               'disabled', 'errors'
#               'warnings', 'all', or 'debug'
VERBOSITY='all'

############################################
##########     SAM_Processing     ##########
############################################

#   Specify how you would like your SAM files to be processed
#       Choose from:
#           'picard' (recommended) or 'samtools'
METHOD=samtools

#   What are our QSub settings for SAM_Processing?
#       Below are the recommended settings
SP_QSUB="mem=22gb,nodes=1:ppn=8,walltime=24:00:00"

#   Where is the list of read-mapped samples?
#       To generate this list, use sample_list_generator.sh
#       located at /sequence_handling/OldScripts/sample_list_generator.sh
MAPPED_LIST=/panfs/roc/scratch/liux1299/WBDC_Inversions_Project/seq_handling_parts_ref/WBDC_LianaPop/Read_Mapping/WBDC_LianaPop_RM_list.txt
#MAPPED_LIST=/panfs/roc/scratch/liux1299/WBDC_Inversions_Project/seq_handling_parts_ref/WBDC_LianaPop/Read_Mapping/WBDC_LianaPop_RM_re-run.txt

#   The next four variables are only used if processing with Picard
#   If using SAMtools, leave these variables blank

#   What is the full file path for the Picard jar file?
PICARD_JAR=/panfs/roc/itascasoft/picard/2.1.1/picard.jar

#   What is the most amount of memory that we can use?
#       Please stylize as #g for gigabytes: ex 15g
MAX_MEM=22g

#   What is the maximum number of file handles that we can use?
#       For UNIX systems, the per-process maximum number of files
#           that can be open may be found with 'ulimit -n'
#       We recommend setting MAX_FILES to be slightly under this value
MAX_FILES=1000

#   Where should Picard store temporary files?
#       If you've encountered issues with running out of temp space
#           with picard, you can optionally specify a temp directory
#       Otherwise, leave blank
TMP=/panfs/roc/scratch/liux1299/seq_handling/tmp

############################################
##########    Coverage_Mapping    ##########
############################################

#   What are our Qsub settings for Coverage_Mapping?
#       Below are the recommended settings
CM_QSUB="mem=12gb,nodes=1:ppn=8,walltime=24:00:00"

#   Where is the list of finished BAM files?
#       To generate this list, use sample_list_generator.sh
#       located at /sequence_handling/OldScripts/sample_list_generator.sh
BAM_LIST=/panfs/roc/groups/9/morrellp/shared/Projects/WBDC_inversions/sequence_handling/WBDC_LianaPop/SAM_Processing/SAMtools/Finished/BAM_list.txt

#   Where is the reference annotation file (GFF or BED)?
#       Include the full file path.
REF_ANN=/home/morrellp/liux1299/Shared/References/Reference_Sequences/Barley/Morex/captured_50x.bed

############################################
##########    Indel_Realignment   ##########
############################################

#   What are our Qsub settings for Indel_Realignment?
#       Below are the recommended settings
IR_QSUB="mem=22gb,nodes=1:ppn=4,walltime=24:00:00"

#   Where is the list of processed BAM files located?
#       To generate this list, use sample_list_generator.sh
#       located at /sequence_handling/OldScripts/sample_list_generator.sh
BAM_LIST_NAME=

#   What is the full file path for the GATK jar file?
GATK_JAR=

#   What is the most amount of memory we can use for GATK?
#       We suggest no less than 4 GB
#       Please stylize as #g: ex 4g
MAX_MEMORY=22g

#   What model are we using for indel realignment?
#       Choose from:
#           'KNOWNS_ONLY', 'USE_READS'
#           or 'USE_SW'
#       Below is the default
MODEL=

#   What log of odds score should we use?
#       Below is the default
LOG_ODDS=0.4

#   Where is the VCF file describing known indels?
KNOWN_INDELS=

#   What are our target intervals?
#       If not generated, leave blank and we will generate for you
#       Be sure to increase the walltime in IR_QSUB to allow for the creation
TARGET_INTERVALS=

############################################
##########      Dependencies      ##########
############################################

#   This section defines installations to
#       various dependencies for sequence_handling
#   If you are able to use a module system for
#       dependencies, then uncomment the lines starting
#       with 'module load'
#   If you need to install a dependency from source,
#       then uncomment the lines for the dependency and the
#       'export PATH=', and write the full path to the executable
#       for the program. For example:
#       PARALLEL=${HOME}/software/parallel-20151122/bin/parallel
#   If you have a system-wide installation for a program, you can
#       leave all lines commented out. sequence_handling will find
#       system-wide installed programs automatically.

#   Do we have GNU parallel installed
module load parallel
#PARALLEL=
#export PATH=${PARALLEL}:${PATH}

#  Do we have Bioawk installed?
#BIOAWK=
#export PATH=${BIOAWK}:${PATH}

#   Do we have FastQC installed?
module load fastqc
#FASTQC=
#export PATH=${FASTQC}:${PATH}

#   Do we have Seqqs installed?
#SEQQS=
#export PATH=${SEQQS}:${PATH}

#   Do we have Sickle installed?
#SICKLE=
#export PATH=${SICKLE}:${PATH}

#   Do we have Scythe installed?
SCYTHE=/panfs/roc/groups/9/morrellp/shared/Software/scythe/scythe
export PATH=${SCYTHE}:${PATH}

#   Do we have R installed?
module load R/3.3.0
#R=
#export PATH=${R}:${PATH}

#   Do we have BWA installed?
module load bwa
#BWA=
#export PATH=${BWA}:${PATH}

#   Do we have SAMTools installed?
module load samtools
#SAMTOOLS=
#export PATH=${SAMTOOLS}:${PATH}

#   Do we have BEDTools 2.23 installed?
#module load bedtools
BEDTOOLS=/panfs/roc/groups/9/morrellp/hoffmanp/software/bedtools2/bin
export PATH=${BEDTOOLS}:${PATH}

#   Do we have Java installed?
module load java
#JAVA=
#export PATH=${JAVA}:${PATH}

#   Do we have the Fastx Toolkit installed?
#module load fastx_toolkit
#FASTX_TOOLKIT=
#export PATH=${FASTX_TOOLKIT}:${PATH}
